server:
  port: 9090

spring:
  application:
    name: hubble-gateway
  profiles:
    active: test

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: hubble-test
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: hubble-test


  config:
    import:
      - optional:nacos:test.yml